name: Build APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user --upgrade buildozer Cython virtualenv
          
      - name: Set environment variables
        run: |
          echo "APP_ANDROID_ACCEPT_SDK_LICENSE=1" >> $GITHUB_ENV
          echo "BUILDOZER_WARN_ON_ROOT=0" >> $GITHUB_ENV
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Add Buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Build with Buildozer
        run: |
          cd ${{ github.workspace }}
          buildozer android debug
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
